id: 0
name: DCS_Basic
# ==== data ====
root_path: /mnt/data/arty/data/IT-GAN
data_path: data
checkpoint_path: checkpoints
generator_path: G_Pretrained
dataset: CIFAR10
mode:  ITGAN
anchors_path: Base
exp: 0
# ==== training ====
batch_size: 128
num_workers: 0
num_epochs: 10
lr: 0.001
weight_decay: 0.00005
model_name: resnet18_32x32
pretrained: False
augmentations: color_crop_cutout_flip_scale_rotate
shuffle: True
unfreeze_after: 0.2
# ==== compute ====
verbose: True
save: True
device: cuda
nodes: [0]
jobs_per_node: 1

