id: 0
name: DCS_S_10
# ==== data ====
root_path: /mnt/data/arty/data/IT-GAN
data_path: data
checkpoint_path: checkpoints
generator_path: G_Pretrained
dataset: CIFAR10
mode$: [
  ITGAN,
  GAN_Inversion,
  Random,
] 
strategy$: 
  - name: Static
    args: {}
  - name: RandomNoise
    args: 
      step_size@: [float, 0.00001, 1, log]
      reset_every@: [int, 1, 10, uniform_1]
  - name: EilertsenEscape 
    args:
      lr@: [float, 0.0001, 10, log]
      weight_decay@: [float, 0.000001, 0.1, log]
      reset_every@: [int, 1, 10, uniform_1]
  - name: LPInversion
    args:
      lr@: [float, 0.0001, 10, log]
      weight_decay@: [float, 0.000001, 0.1, log]
      alpha@: [float, 0.0, 1, uniform]
anchors_path: Base
exp: 0
# ==== training ====
batch_size: 256
num_workers: 0
num_epochs: 10
lr@: [float, 0.0001, 0.1, log]
# lr: 0.01
weight_decay@: [float, 0.000001, 0.1, log]
# weight_decay: 0.00005
model_name: resnet18.a1_in1k
drop_rate: 0.1
pretrained: False
augmentations: color_crop_cutout_flip_scale_rotate
shuffle: True
unfreeze_after: 0.2
# ==== compute ====
verbose: False
save: False
device: cuda
nodes: [0, 1, 2, 3]
jobs_per_node: 2
iterations: 2
# ==== optuna ====
trials: 1000
db: mysql+pymysql://root:root@172.16.1.129/dcs
